services:
  db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - /var/lib/postgres
    ports:
      - "5332:5432"
    networks:
      - db

networks:
  db:
    driver: bridge
volumes:
  db:
