spring:
  application:
    name: market-data
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5332/market
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: true
  data:
    elasticsearch:
      cluster-names: es-docker-cluster
    data:
      elasticsearch:
        cluster-node: localhost:9200
server:
  port: 9090





