spring:
  application:
    name: market-data
  datasource:
    url: jdbc:postgresql://localhost:5332/marketdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: true
  data:
    elasticsearch:
      cluster-names: es-docker-cluster
    data:
      elasticsearch:
        cluster-node: localhost:9200
  task:
    scheduling:
      pool:
        size=10:
order-service:
  exchange:
    one: https://exchange.matraining.com/
    two: https://exchange2.matraining.com/




